/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


/**
 *
 * @author prana
 */
public class FreezeAccountPane extends javax.swing.JFrame {
    javax.swing.JFrame prevPane;
    /**
     * Creates new form FreezeAccountPane
     * @param prevPane
     */
    
    public FreezeAccountPane(javax.swing.JFrame prevPane) {
        this.prevPane = prevPane;
        initComponents(); 

        this.setLocationRelativeTo(null);
        this.nameLb.setText("Hi, " + root.OBI.envVars.get("fullName"));
        Double balance = api.Balance.balance();
        this.balanceLb.setText("Current Balance: Rs " +  balance);
        this.term1Lb.setText("1. The account doesn't allow outgoing transactions");
        this.term2Lb.setText("2. It can result from a court order or be initiated by the financial institution itself.");
        this.term3Lb.setText("3. Open transactions are canceled, and checks presented on a frozen account aren't honored.");
        this.term4Lb.setText("4. The account holder can still deposit money but may not be able to withdraw it");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameLb = new javax.swing.JLabel();
        accountLb = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        balanceLb = new javax.swing.JLabel();
        term1Lb = new javax.swing.JLabel();
        term2Lb = new javax.swing.JLabel();
        term4Lb = new javax.swing.JLabel();
        term3Lb = new javax.swing.JLabel();
        txtLb = new javax.swing.JLabel();
        freezeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Online Bank of India");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nameLb.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nameLb.setText("Hi, SHIVAM KUMAR");

        accountLb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        accountLb.setText("ACCOUNT NUMBER: 123456789087");

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("↜ go back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setText("Agree");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        balanceLb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        balanceLb.setText("ACCOUNT NUMBER: 123456789087");

        term1Lb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        term1Lb.setText("ACCOUNT NUMBER: 123456789087");

        term2Lb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        term2Lb.setText("ACCOUNT NUMBER: 123456789087");

        term4Lb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        term4Lb.setText("ACCOUNT NUMBER: 123456789087");

        term3Lb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        term3Lb.setText("ACCOUNT NUMBER: 123456789087");

        txtLb.setText("Terms & Conditions");

        freezeBtn.setBackground(new java.awt.Color(0, 102, 102));
        freezeBtn.setForeground(new java.awt.Color(255, 255, 255));
        freezeBtn.setText("Freeze");
        freezeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freezeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(term2Lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(term3Lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(freezeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(term1Lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accountLb, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(balanceLb, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLb, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addComponent(term4Lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(209, 209, 209))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceLb)
                .addGap(51, 51, 51)
                .addComponent(txtLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(term1Lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(term2Lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(term3Lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(term4Lb)
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(freezeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        prevPane.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_backBtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void freezeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freezeBtnActionPerformed
        if (jCheckBox1.isSelected()) {
            root.SqlConnector x = new root.SqlConnector();
            
            try {
                int hit = x.connection
                        .createStatement()
                        .executeUpdate("UPDATE users SET isFreezed = 1 WHERE accountNumber = "
                                + root.OBI.envVars.get("accountNumber"));
                if (hit == 1) {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        javax.swing.JFrame r = new Dialog("Your Account is Freezed.");
                        r.setVisible(true);
                        r.setLocationRelativeTo(null);
                    });
                    
                }
                
                x.connection.close();
            }
            catch (java.sql.SQLException err) {
                System.out.println("ERROR: " + err);
            }
        }
    }//GEN-LAST:event_freezeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLb;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel balanceLb;
    private javax.swing.JButton freezeBtn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel term1Lb;
    private javax.swing.JLabel term2Lb;
    private javax.swing.JLabel term3Lb;
    private javax.swing.JLabel term4Lb;
    private javax.swing.JLabel txtLb;
    // End of variables declaration//GEN-END:variables
}
